In [61]:
import numpy as np
import math
import matplotlib.pyplot as plt
%matplotlib inline

In [62]:
#set means
m_rmg=np.array([x for x in range (0,31) if x%2==1])
m_fam=np.array([x for x in range (0, 31) if x%2==0])

In [125]:
class Person:
    
    def create_cells(self):
        self.cell_list=np.zeros((self.cell_count, self.fcount))
        
        
        for i in range (0, self.fcount):
            self.cell_list[:,i ]= np.random.normal(self.m[i], self.sigm, self.cell_count)
    
    
    def __init__(self, t):
        
        
        if t=='rmg':
            self.m=np.array([x for x in range (0, 31) if x%2==0])
            print(self.m)

        if t=='fam':
            self.m=np.array([x for x in range (0,31) if x%2==1])
            
            print(self.m)
            
        self.cell_count=np.random.randint(10, 30)
        self.fcount=15
        #set variace
        self.sigm=1
        
        self.create_cells()
        self.mean=np.mean(self.cell_list)
    
    def get_mean(self, t):
        
        return np.mean(self.cell_list, axis=0)[t]
    
    def get_min(self, t):
        
        return min(self.cell_list[:, t])
    
    def get_max(self, t):
        
        return max(self.cell_list[:, t])
    
    
    
    
        
        
        
        
    
    
            
            
        

In [126]:
class people:
    def __init__(self, count, who):
        
        self.persons=[]
        self.count=count
        self.who=who
        
        for i in range(0, count):
            self.persons.append(Person(who))
        self.persons=np.array(self.persons)
    
        
    def get_mean(self, t, k): 
        return self.persons[k].get_mean(t)

    def get_min(self,t, k):
        return self.persons[k].get_min(t)
    
    def get_max(self, t, k):
        return self.persons[k].get_max(t)
    
    def get_a_min(self, t, ex=-1):
        y_min=[self.get_min(t, k) for k in range(0, self.count) if not k==ex]
        return min(y_min)
    
    def get_a_max(self, t, ex=-1):
        y_min=[self.get_min(t,k) for k in range(0, self.count) if not k==ex]
        return max(y_min)
    
    def get_b_min(self, t, ex=-1):
        y_max=[self.get_max(t, k) for k in range(0, self.count) if not k==ex]
        return min(y_max)
    
    def get_b_max(self, t, ex=-1):
        y_max=[self.get_max(t, k) for k in range(0, self.count) if not k==ex]
        return max(y_max)
    
    def get_c_min(self, t, ex=-1):
        y_mean=[self.get_mean(t, k) for k in range(0, self.count) if not k==ex]
        return min(y_mean)
    
    def get_c_max(self, t, ex=-1):
        y_mean=[self.get_mean(t, k) for k in range(0, self.count) if not k==ex]
        return max(y_mean)
    
    def in_a(self, x, t, ex=-1):
        f1=(x>=self.get_a_min(t, ex))
        f2=(x<=self.get_a_max(t, ex))
        if f1 and f2:
            return 1
        else:
            return 0
    
    def in_b(self, x, t, ex=-1):
        f1=(x>=self.get_b_min(t, ex))
        f2=(x<=self.get_b_max(t, ex))
        if f1 and f2:
            return 1
        else:
            return 0
        
    def in_c(self, x, t, ex=-1):
        f1=(x>=self.get_c_min(t, ex))
        f2=(x<=self.get_c_max(t, ex))
        if f1 and f2:
            return 1
        else:
            return 0

In [127]:
count_rmg=25
count_fam=25
count_feat=15

In [128]:
#create objects
rmg=people(count_rmg, 'rmg')
fam=people(count_fam, 'fam')
rmg.persons[0].cell_list

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


array([[-0.35901384,  1.45819007,  1.23651363,  6.40682252,  5.72725787,
        11.02275273, 13.77507329, 13.75026755, 16.79311611, 17.91450102,
        18.95464468, 22.08736582, 23.30910241, 23.30228554, 28.89268427],
       [-0.44232578,  1.01965674,  2.8719042 ,  6.17172292,  8.44049634,
        10.13287709, 13.17279961, 14.11713878, 15.61453221, 19.07670514,
        18.44955251, 23.67390118, 25.32545933, 26.90256623, 27.73728878],
       [ 1.46111105,  0.45588003,  5.63355817,  5.31972325,  8.30266078,
        11.10775577, 11.89409349, 13.8066086 , 14.43690521, 19.6862337 ,
        20.26166318, 22.01998048, 22.57738773, 25.16426839, 27.3790812 ],
       [ 0.68217564,  0.85750693,  4.2148692 ,  7.03503429,  7.67616034,
         8.98608438, 11.68301797, 13.18069766, 14.90813259, 17.88552961,
        20.5859403 , 21.08624696, 24.42213365, 25.47164522, 28.9366783 ],
       [-0.12386568,  0.54849149,  4.43680639,  5.09948173,  9.61724323,
        10.09726439, 12.05073337, 14.27725327, 

In [129]:
def conf_int(h, m, g):
    
    h1=(h*m+g**2/2.0-g*math.sqrt(h*(1-h)*m+g**2/4.0))/(m+g**2)
    h2=(h*m+g**2/2.0+g*math.sqrt(h*(1-h)*m+g**2/4.0))/(m+g**2)
    
    return (h1, h2)

In [99]:
def p_stat(x, y):
    x=np.sort(x)
    y=np.sort(y)
    
    N=x.size*(x.size-1)/2.0
    L=0
    
    for i in range (0, x.size-1):
        for j in range(i+1, x.size):
            
            pij=(j-i)/float(x.size+1)
            A=0
            
            for k in range(0, y.size):
                
                
                if (x[i]<y[k] and y[k]<x[j]) :
                    A+=1
            
            h=float(A)/y.size
            
            p=conf_int(h, N, 3)
            
            if pij>p[0] and pij<p[1] :
                if h!=0:
                    L+=1
                else:
                    p=np.random.binomial(1,0.7)
                    L+=p
    
    return float(L)/N

In [100]:

    def max_dist(M):
        max_d=0
        ind=[]
        for i in range (0, len(M)-1):
            for j in range (i+1, len(M) ):
                if np.linalg.norm(M[i]-M[j])>max_d:
                    max_d=np.linalg.norm(M[i]- M[j])
                    ind=[i, j]
        return (max_d, ind)

In [101]:
class line():
    def __init__(self, mass, point=True):
        if point:
            self.A=mass[1][1]-mass[0][1]
            self.B=mass[0][0]-mass[1][0]
            self.C=mass[0][1]*(mass[1][0]-mass[0][0])-mass[0][0]*(mass[1][1]-mass[0][1])
        else:
            self.A=mass[0]
            self.B=mass[1]
            self.C=mass[2]
            
    def funk1(self, p1,p2):
        self.A=p2[1]-p1[1]
        self.B=p1[0]-p2[0]
        self.C=p1[1]*(p2[0]-p1[0])-p1[0]*(p2[1]-p1[1])
    def eval_y(self, x):
        return (-self.A*x-self.C)/self.B
    
    def evalv(self, p):
        return self.A*p[0]+self.B*p[1]+self.C
    
    def lplot(self, a, b):
        x=np.arange(a, b, 0.01)
        y=[]
        for i in x:
            y.append(self.eval_y(i))
        plt.plot(x, y)
  
        
        
    def intersect(self,l):
        x= self.B*l.C-l.B*self.C
        y=l.A*self.C-self.A*l.C
        w=self.A*l.B-l.A*self.B
        x=x/w
        y=y/w
        return np.array([x, y])
    
    def dist(self,p):
        return (self.A*p[0]+self.B*p[1]+self.C)/math.sqrt(self.A**2+self.B**2)
    
    def on_one_side(self, point1, point2):
        if self.evalv(point1)*self.evalv(point2)>=0:
            return True
        else :
            return False
        
        

In [102]:
def two_max(l,M):
    d1=0
    d2=0
    ind1=-1
    ind2=-1
    for i in range (0, len(M)):
        if l.evalv(M[i])>=0:
            if l.dist(M[i])>d1:
                ind1=i
                d1=l.dist(M[i])
        if l.evalv(M[i])<=0:
            if abs (l.dist(M[i]))>d2:
                ind2=i
                d2=abs(l.dist(M[i]))
    return [ind1, ind2]
            

In [103]:
def left_down(intersect):
    ind=-1
    mind=min([x[1] for x in intersect])
    ind=[x[0] for x in zip (range(0, len(intersect)), intersect) if x [1][1]==mind]
    if len(ind)>1:
        if intersect[ind[0]][0]>intersect[ind[1]][0]:
            ind = ind[1]
        else:
            ind=ind[0]
    else:
        ind=ind[0]
    return ind

In [104]:
def shift(M, p):
    for i in range(0, len(M)):
        M[i][0]-=p[0]
        M[i][1]-=p[1]
  
    return M

In [105]:
def neigh(M, ind):
    max_d=0
    ind1=-1
    for i in range (0, len(M)):
        if np.linalg.norm(M[i]- M[ind])>max_d:
            max_d=np.linalg.norm(M[i]-M[ind])
            ind1=i
    res=[]
    for i in range (0, len(M)):
        if i!=ind and i!=ind1:
            res.append(i)
    return res

In [106]:
def rotating(M, p1, p2):
    p1=p1/np.linalg.norm(p1)
    p2=p2/np.linalg.norm(p2)
    a=np.zeros((2, 2))
    a[0, 0]=p1[0]
    a[1, 0]=p1[1]
    a[0, 1]=p2[0]
    a[1, 1]=p2[1]
    a_inv=np.linalg.inv(a)
    for i in range (0, len(M)):
        M[i]=np.dot(a_inv, M[i])
    return [M, a]

In [107]:
def compr(M,iint,  left_d, neib):
    a=np.linalg.norm(left_d-neib[0])
    b=np.linalg.norm(left_d-neib[1])
    if neib[0][0]==0:
        alph=a/b
    else:
        alph=b/a
   
    for i in range (0, len(M)):
        M[i][0]*=alph
    for i in range (0, len(iint)):
        iint[i][0]*=alph
    return M, iint, alph
    

In [108]:
def find_r(M, ct):
    r=0
    for i in range (0, len(M)):
        if np.linalg.norm(ct-M[i])>r:
            r=np.linalg.norm(ct-M[i])
    return r
    

In [109]:
def ell(a, ct, r, sh, alph):
    x=[]
    y=[]
    for t in np.arange(0, 2*np.pi, 0.001):
        xc=(r*math.cos(t)+ct[0])
        yc=r*math.sin(t)+ct[1]
        xc/=alph
        
        x.append(xc)
        y.append(yc)
    return [x, y]
    

In [110]:
def create_M(x, y):
    M=[]
    for i in range (0, len(x)):
        M.append(np.array([x[i], y[i]]))
    return np.array(M)

In [111]:
def lplot(l, a, b):
    y=[]
    x=np.arange(a, b, 0.01)
    for i in x:
        y.append (l.eval_y(i))
    plt.plot(x, y)

In [112]:
def scopy(M):
    M_copy=[]
    for i in np.arange(0, len(M)):
        M_copy.append(np.array([M[i][0], M[i][1]]))
    return M_copy

In [113]:
def cplot(ct, r):
    x=[]
    y=[]
    for t in np.arange(0, 2*np.pi, 0.01):
        x.append(ct[0]+r*math.cos(t))
        y.append(ct[1]+r*math.sin(t))
    plt.plot(x, y)

In [114]:
class elips():
    def __init__(self, ct=[0, 0],points=[],  shift=[0, 0], r=1, alpha=1, matr_rot=[] ):
        self.ct=ct
        self.points=points
        self.alpha=alpha
        self.matr_rot=matr_rot
        self.sh=shift
        self.r=r
    def transform_inv(self, point):
        point=point-self.ct
        a_inv=np.linalg.inv(self.matr_rot)
        point=np.dot(a_inv, point)
        point[0]*=self.alpha
        return point
        
    def in_elips(self, point):
        point= self.transform_inv(point)
        if sum(point**2)<=self.r*self.r:
            return True
        else:
            return False
        
    def el_plot(self):
        for i in range(0, len(self.points)):
            plt.plot(self.points[i][0], self.points[i][0])
        
            
        
        
        
        

In [115]:
def elips_pet(M):
    M1=scopy(M)
    max_d, ind=max_dist(M)
    l=line([M[ind[0]], M[ind[1]]])
 
 
    ind1, ind2=two_max(l, M)
  
    if ind1==-1 or ind2==-1:
        if ind1==-1:
            ind1=ind2
        c1=l.evalv(M[ind1])
        l1=line([l.A, l.B, l.C-c1], False)
        l2=l
    else:
        
        c1=l.evalv(M[ind1])
        c2=l.evalv(M[ind2])
     
        l1=line([l.A, l.B, l.C-c1], False)
    
        l2=line([l.A, l.B, l.C-c2], False)
    
    l3=line([-l.B, l.A, 0], False)
    l4=line([-l.B, l.A, 0], False)
    
    c3=l3.evalv(M[ind[0]])
    c4=l3.evalv(M[ind[1]])
    l3.C=-c3
    l4.C=-c4
    
    intersect=[]
    intersect.append(l2.intersect(l4))
    intersect.append(l2.intersect(l3))
    intersect.append(l1.intersect(l4))
    intersect.append(l1.intersect(l3))
    
    left_d=left_down(intersect)
    M1=shift(M1,intersect[left_d])
    
    neib=neigh(intersect, left_d)
    intersect1=scopy(intersect)
    
    intersect1=shift(intersect1, intersect[left_d])

    rot=[]
    int2=scopy(intersect1)
 
    [M1, matr_rot]=rotating(M1, intersect1[neib[0]], intersect1[neib[1]])
    
    [int21, matr_rot]=rotating(int2,intersect1[neib[0]], intersect1[neib[1]] )
    
    
  
    
   
    int3=scopy(int2)
    M1,int3,  alph=compr(M1, int3, int2[left_d], [int2[neib[0]],int2[neib[1]]] )
  
   
     #center of the square
    a=np.linalg.norm(int3[left_d]-int3[neib[0]])
    ct=np.array([a/2, a/2])

    r=find_r(M1, ct)

    
    [x, y]=ell(matr_rot,ct, r, intersect[left_d], alph )
    ct[0]/=alph
    plt.figure(5)
    elps=create_M(x, y)
    for i in range (0, len(elps)):
        elps[i]=np.dot(matr_rot, elps[i])
    ct=np.dot(matr_rot, ct)
    for i in range(0, len(elps)):
        elps[i]+=intersect[left_d]
    ct+=intersect[left_d]
  

    return elips(ct, elps, intersect[left_d],r, alph, matr_rot  )
  
   

   
  
 

    
   
    

In [116]:
def A1(point_ar, E_ar, t, s):
    return E_ar[t][s].in_elips(point_ar[t][s].get_point())

def A3 (point_ar, E_ar, E_two_ar, t, s):
    f1=E_ar[t][s].in_elips(point_ar[t][s].get_point())
    f2=E_two_ar[t][s].in_elips(point_ar[t][s].get_point())
    
    return (f1 and not f2) 

def B1(point_ar, E_ar,E_two_ar, t, s):
    ct1=E_ar[t][s].ct
    ct2=E_two_ar[t][s].ct
    a=ct2[1]-ct1[1]
    b=ct1[0]-ct2[0]
    l_mperp=line([-b, a, 0], False)
    mean_point=(ct1+ct2)/2
    c=l_mperp.evalv(mean_point)
    l_mperp.C=-c
    if l_mperp.on_one_side(point_ar[t][s].get_point(),E_ar[t][s].ct ):
        return True
    else:
        return False
    
def C1(point_ar_p, point_ar_d, E_arp, E_two_arp, E_ard, E_two_ard, t, s ):
    
    f1=A3(point_ar_p, E_arp, E_two_arp, t, s)
    f2=A3(point_ar_d, E_two_ard, E_ard, t, s)
        
    return (f1 or f2)

def C2(point_ar_p, point_ar_d, E_arp, E_two_arp, E_ard, E_two_ard, t, s ):
    f1=A3(point_ar_p, E_two_arp, E_arp, t, s)
    f2=A3(point_ar_d, E_ard, E_two_ard, t, s)
    return (f1 or f2)

def C3(point_ar_p, point_ar_d, E_arp,E_two_ard, t, s):
    f1=A1(point_ar_p, E_arp, t, s)
    f2=A1(point_ar_d, E_two_ard, t, s)
    return (f1 or f2)

def C4(point_ar_p, point_ar_d, E_two_arp,E_ard, t, s):
    f1=A1(point_ar_p, E_two_arp, t, s)
    f2=A1(point_ar_d, E_ard, t, s)
    return (f1 or f2)

def C5(point_ar_p, point_ar_d, E_arp, E_two_arp, E_ard, E_two_ard, t, s ):
    f1=B1(point_ar_p, E_arp,E_two_arp, t, s)
    f2=B1(point_ar_d, E_two_ard,E_ard, t, s)
    return (f1 or f2)


def C6 (point_ar_p, point_ar_d, E_arp, E_two_arp, E_ard, E_two_ard, t, s ):
    f1=B1(point_ar_p, E_two_arp,E_arp, t, s)
    f2=B1(point_ar_d, E_ard,E_two_ard, t, s)
    return (f1 or f2)

In [117]:
def create_pstat(x_ar, y_ar, count_feat, left):
    P_stat=np.zeros((len(x_ar), count_feat))
    for i in range(0, len(x_ar)):
        if i!=left:
            x_cur=x_ar[i].cell_list
    
            for f in range (0, count_feat):
                celist=[]
                for j in [z for z in range(0, len(y_ar)) if not z==i and z!=left]:
                    for cel in range (0, len(y_ar[j].cell_list[:, f])):
                        celist.append(y_ar[j].cell_list[cel, f])
                P_stat[i, f]=p_stat(x_cur[:, f], celist)
    
    
    return P_stat

def create_p(x_ar, y_ar, count_feat):
    P_stat=np.zeros((len(x_ar), count_feat))
    for i in range(0, len(x_ar)):
            x_cur=x_ar[i].cell_list
    
            for f in range (0, count_feat):
                celist=[]
                for j in [z for z in range(0, len(y_ar)) if not z==i ]:
                     for cel in range (0, len(y_ar[j].cell_list[:, f])):
                            celist.append(y_ar[j].cell_list[cel, f])
                    
                P_stat[i, f]=p_stat(x_cur[:, f], celist)
  
    return P_stat


def create_p_two(x_ar, y_ar, count_feat):
    P_stat=np.zeros((len(x_ar), count_feat))
    for j in [z for z in range(0, len(x_ar)) ]:
   
        for f in range (0, count_feat):
                 celist=[]
                 for i in range(0, len(y_ar)):
                     for cel in range (0, len(y_ar[i].cell_list[:, f])):
                            celist.append(y_ar[i].cell_list[cel, f])
                   
                
                 P_stat[j, f]=p_stat( x_ar[j].cell_list[:, f], celist)
    
    return P_stat





def create_pstat_two(x_ar, y_ar, count_feat, left):
    P_stat=np.zeros((len(x_ar), count_feat))
    for j in [z for z in range(0, len(x_ar)) if not z==left]:
  
        
        for f in range (0, count_feat):
            celist=[]
            for i in range(0, len(y_ar)):
                 for cel in range (0, len(y_ar[i].cell_list[:, f])):
                        celist.append(y_ar[i].cell_list[cel, f])
                   
            P_stat[j, f]=p_stat( x_ar[j].cell_list[:, f], celist)
  
    return P_stat



def create_pstat_two_lt(x_ar, y_ar, count_feat, left):
    P_stat=np.zeros((len(x_ar), count_feat))
    for j in [z for z in range(0, len(x_ar)) ]:
        for f in range (0, count_feat):
            celist=[]
            for i in range(0, len(y_ar)):
                if i!=left:
                    for cel in range (0, len(y_ar[i].cell_list[:, f])):
                        celist.append(y_ar[i].cell_list[cel, f])
            P_stat[j, f]=p_stat( x_ar[j].cell_list[:, f], celist)
    return P_stat


def Mplot(M):
    for i in range(0, len(M)):
        plt.plot(M[i][0], M[i][1], 'r+')
        
def create_elps(p_mean):
    n=p_mean.shape[1]

    E=[]

    for i in range (0, p_mean.shape[1]):
        E_i=[]
        for j in range (0, p_mean.shape[1]):
            if i!=j and i<j:
                M=create_M(p_mean[:, i], p_mean[:, j])
                ell1=elips_pet(M)
                E_i.append(ell1)
                
              
            else:
                E_i.append(elips())
        E.append(E_i)
    return E


def create_p_cur(x_ar, left, count_feat):
    p_cur=np.zeros((1, count_feat))
    x_cur=x_ar[left].cell_list
    for f in range (0, count_feat):
        celist=[]
        for j in [z for z in range(0, len(x_ar)) if z!=left]:
            for cel in range (0, len(x_ar[j].cell_list[:, f])):
                    celist.append(x_ar[j].cell_list[cel, f])
        p_cur[0,  f]=p_stat(x_cur[:, f], celist)
  
    return p_cur



def create_p_cur_two(x_ar, y_ar, left, count_feat):
    p_cur_two=np.zeros((1, count_feat))
    for f in range (0, count_feat):
        celist=[]
        for i in range(0, len(y_ar)):
            for cel in range (0, len(y_ar[i].cell_list[:, f])):
                celist.append(y_ar[i].cell_list[cel, f])
    p_cur_two[0,  f]=p_stat( x_ar[left].cell_list[:, f], celist)
    
    
    return p_cur_two


    
    
def create_points(pstat):
    res=[]
    for i in range (0, len(pstat)-1):
        res1=[]
        for j in range(0, len(pstat) ):
            if j<=i:
                res1.append(0)
            else:
                res1.append(pointt(pstat[i], pstat[j]))
        res.append(res1)
       
    return res


def find_h(pp, dd, E, E_two, D, D_two,count_feat):
    h=np.zeros(6)
    for i in range (0, count_feat-1):
        for j in range (i+1, count_feat):
            if C1(pp, dd, E, E_two, D, D_two, i, j):
                h[0]+=1
            if C2(pp, dd, E, E_two, D, D_two, i, j ):
                h[1]+=1
            if C3(pp, dd, E, D_two, i, j):
                h[2]+=1
            if C4(pp, dd, E_two, D, i, j):
                h[3]+=1
            if C5(pp, dd, E, E_two, D, D_two, i, j ):
                h[4]+=1
            if C6 (pp, dd, E, E_two, D, D_two, i, j ):
                h[5]+=1
    
    return h/(float(count_feat*(count_feat-1)/2))



    
    
















In [118]:
class pointt:
    def __init__(self, x, y):
        self.x=x
        self.y=y
    def get_point(self):
        return np.array([self.x, self.y])

In [119]:
def find_h_all(x_ar, y_ar, count_feat, who):
    
  
    p_mean=create_p(y_ar, y_ar, count_feat)
    p_mean_two=create_p_two(y_ar, x_ar, count_feat)
    p_mean_two+=np.random.normal(0, 0.003, p_mean_two.shape)
    E=create_elps(p_mean)
    E_two=create_elps(p_mean_two)
    h2=np.zeros((len(x_ar), 6))
    for ex in range (0, len(x_ar)):
   
        d_mean=create_pstat(x_ar, x_ar, count_feat, ex)
        d_mean_two=create_pstat_two(x_ar, y_ar, count_feat, ex)
     
        D_ar=create_elps(d_mean)
        D_ar_two=create_elps(d_mean_two)
        d_cur=create_p_cur(x_ar, ex, count_feat)
        d_cur_two=create_p_cur_two(x_ar, y_ar, ex, count_feat)
        dd=create_points(d_cur[0])
        pp=create_points(d_cur_two[0])
        if who=='fam':
            h2[ex,:]=find_h(pp, dd, E, E_two, D_ar, D_ar_two, count_feat)
        if who == 'rmg':
            h2[ex, :]=find_h(dd, pp, D_ar, D_ar_two, E, E_two, count_feat)
    
    return h2

    
   
       
       
        
   
        
            

   
   


In [120]:
def plott(M, k, l):
    x=[]
    y=[]
    for i in range (0, len(M)):
        x.append(M[i][0])
        y.append(M[i][1])
    k.plot(x, y, label=l)

In [121]:
def plot_set(x, y):
    for i in range (0, len(x)):
        plt.plot(x[i], y[i], 'r+')
        

In [122]:
def MMplot(M, pr):
    for i in range(0, len(M)):
        plt.plot(M[i][0], M[i][1], pr)
        

In [130]:
find_h_all(fam.persons, rmg.persons, count_feat, 'fam')

array([[0.        , 0.6       , 0.22857143, 0.82857143, 0.02857143,
        1.        ],
       [0.01904762, 0.5047619 , 0.41904762, 0.9047619 , 0.01904762,
        1.        ],
       [0.        , 0.5047619 , 0.47619048, 0.98095238, 0.03809524,
        1.        ],
       [0.00952381, 0.53333333, 0.37142857, 0.8952381 , 0.04761905,
        1.        ],
       [0.0952381 , 0.18095238, 0.77142857, 0.85714286, 0.19047619,
        1.        ],
       [0.        , 0.27619048, 0.72380952, 1.        , 0.05714286,
        1.        ],
       [0.00952381, 0.5047619 , 0.46666667, 0.96190476, 0.02857143,
        1.        ],
       [0.03809524, 0.13333333, 0.84761905, 0.93333333, 0.21904762,
        1.        ],
       [0.01904762, 0.64761905, 0.33333333, 0.96190476, 0.03809524,
        1.        ],
       [0.04761905, 0.05714286, 0.93333333, 0.93333333, 0.14285714,
        1.        ],
       [0.04761905, 0.24761905, 0.68571429, 0.88571429, 0.0952381 ,
        1.        ],
       [0.        , 0

<Figure size 432x288 with 0 Axes>

In [131]:
find_h_all(fam.persons, rmg.persons, count_feat, 'rmg')

array([[0.60952381, 0.        , 0.82857143, 0.21904762, 1.        ,
        0.02857143],
       [0.47619048, 0.02857143, 0.8952381 , 0.44761905, 1.        ,
        0.04761905],
       [0.51428571, 0.        , 0.98095238, 0.47619048, 1.        ,
        0.03809524],
       [0.51428571, 0.00952381, 0.88571429, 0.38095238, 1.        ,
        0.04761905],
       [0.18095238, 0.0952381 , 0.85714286, 0.77142857, 1.        ,
        0.18095238],
       [0.27619048, 0.        , 1.        , 0.72380952, 1.        ,
        0.05714286],
       [0.5047619 , 0.00952381, 0.96190476, 0.46666667, 1.        ,
        0.03809524],
       [0.12380952, 0.03809524, 0.93333333, 0.85714286, 1.        ,
        0.21904762],
       [0.66666667, 0.01904762, 0.97142857, 0.32380952, 1.        ,
        0.03809524],
       [0.05714286, 0.04761905, 0.93333333, 0.93333333, 1.        ,
        0.14285714],
       [0.22857143, 0.04761905, 0.87619048, 0.6952381 , 1.        ,
        0.0952381 ],
       [0.38095238, 0

<Figure size 432x288 with 0 Axes>

In [148]:
def find_alpha(pep1, pep2, count_feat, who):
    if who=='rmg':
        pep=pep1
    if who=='fam':
        pep=pep2
    alpha=np.zeros((len(pep.persons), 2))
    for ex in range(0, len(pep.persons)):
  
        for t in range (0, count_feat):
            x_mean_t=pep.get_mean( t, ex )
            x_min_t=pep.get_min( t, ex)
            x_max_t=pep.get_max( t, ex)
            alpha[ex, 0]+=pep1.in_a(x_min_t, t, ex)
            alpha[ex,0 ]+=pep1.in_c(x_mean_t, t, ex)
            alpha[ex, 0]+=pep1.in_b(x_max_t, t, ex)
            alpha[ex, 1]+=pep2.in_a(x_min_t, t)
            alpha[ex, 1]+=pep2.in_b(x_max_t, t)
            alpha[ex, 1]+=pep2.in_c(x_mean_t, t)
    return alpha

    

порядковый тест

In [149]:
find_alpha(rmg, fam, count_feat, 'rmg')
        


array([[34.,  0.],
       [44.,  0.],
       [42.,  0.],
       [40.,  0.],
       [38.,  0.],
       [40.,  0.],
       [42.,  0.],
       [35.,  0.],
       [44.,  0.],
       [41.,  0.],
       [43.,  0.],
       [43.,  0.],
       [42.,  0.],
       [38.,  0.],
       [42.,  0.],
       [40.,  0.],
       [44.,  0.],
       [42.,  0.],
       [42.,  0.],
       [43.,  0.],
       [44.,  0.],
       [42.,  0.],
       [45.,  0.],
       [41.,  0.],
       [44.,  0.]])

In [150]:
find_alpha(fam, rmg, count_feat, 'fam')

array([[ 0., 45.],
       [ 0., 45.],
       [ 0., 45.],
       [ 0., 45.],
       [ 0., 45.],
       [ 0., 45.],
       [ 0., 45.],
       [ 0., 45.],
       [ 0., 45.],
       [ 0., 45.],
       [ 0., 45.],
       [ 0., 45.],
       [ 0., 45.],
       [ 0., 45.],
       [ 0., 45.],
       [ 0., 45.],
       [ 0., 45.],
       [ 0., 45.],
       [ 0., 45.],
       [ 0., 45.],
       [ 0., 45.],
       [ 0., 45.],
       [ 0., 45.],
       [ 0., 45.],
       [ 0., 45.]])